<?php declare(strict_types=1);

namespace App\Model;


use App\Core\Entity;
use App\Core\Model;
use App\Entity\Usuario;
use PDO;

class UsuarioModel extends Model
{
    public function __construct(PDO $pdo, string $tableName = "usuario", string $className = Usuario::class)
    {
        parent::__construct($pdo, $tableName, $className);
    }

    public function saveTransaction(Usuario $usuario)
    {
        $fnSaveTransaction = function () use ($usuario) {
            $this->save($usuario);
        };
        $this->executeTransaction($fnSaveTransaction);
    }

    public function find(int $id): Usuario
    {
        return parent::find($id); // TODO: Change the autogenerated stub
    }

    public function validate(Entity $entity): array {

        $errors = [];

        if (empty($entity->getNombre())) {
            $errors[] = "El nombre es obligatorio";
            $entity->setNombre("");


        }
        if (empty($entity->getApellidos())) {
            $errors[] = "Los apellidos son obligatorios";
            $entity->setApellidos("");
        }

        if (empty($entity->getTelefono())) {
            $errors[] = "El teléfono es obligatorio";
            $entity->setTelefono("");
        }

        if (empty($entity->getEmail())) {
            $errors[] = "El email es obligatorio";
            $entity->setEmail("");
        }

        if (empty($entity->getUsername())) {
            $errors[] = "El username es obligatorio";
            $entity->setUsername("");
        }

        if (empty($entity->getPassword())) {
            $errors[] = "El password es obligtorio";
            $entity->setPassword("");

        }


        return $errors;

    }

}